dual_manipulator:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 125

  joint_1_1_v_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_1_1
    pid: {p: 5000, i: 0, d: 0, i_clamp: 100}
  joint_2_1_v_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_2_1
    pid: {p: 5000, i: 0, d: 0, i_clamp: 100}
  joint_3_1_v_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_3_1
    pid: {p: 5000, i: 0, d: 0, i_clamp: 100}
  joint_4_1_v_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_4_1
    pid: {p: 5000, i: 0, d: 0, i_clamp: 100}
  joint_5_1_v_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_5_1
    pid: {p: 5000, i: 0, d: 0, i_clamp: 100}
  joint_6_1_v_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_6_1
    pid: {p: 5000, i: 0, d: 0, i_clamp: 100}

  joint_1_2_v_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_1_2
    pid: {p: 5000, i: 0, d: 0, i_clamp: 100}
  joint_2_2_v_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_2_2
    pid: {p: 5000, i: 0, d: 0, i_clamp: 100}
  joint_3_2_v_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_3_2
    pid: {p: 5000, i: 0, d: 0, i_clamp: 100}
  joint_4_2_v_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_4_2
    pid: {p: 5000, i: 0, d: 0, i_clamp: 100}
  joint_5_2_v_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_5_2
    pid: {p: 5000, i: 0, d: 0, i_clamp: 100}
  joint_6_2_v_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_6_2
    pid: {p: 5000, i: 0, d: 0, i_clamp: 100}